### ISSUE TITLE
Invalid valuationDate in sandbox/webapi/api/v3/netbanking/cz/my/accounts/I141126DXHZ3T/transactions

### ISSUE THREAD

**Issue by timtebeek** [Ceskasporitelna/WebAPI#10]
When calling https://api.csas.cz/sandbox/webapi/api/v3/netbanking/cz/my/accounts/I141126DXHZ3T/transactions
I get a `$.transactions[0].valuationDate` value of `2017-26-14T15:11:30GMT+0100GMT+0100`.
This does not seem to be a valid date format; Can you fix that on your end?

**Comment by timtebeek** [comment]
Any update on this @tomasma5 or @jmachan?

**Comment by jmachan** [comment]
Hello @timtebeek I've got the fix, but it's in the legacy systems, so it will appear with new release in 28.1. 2018. So I would recommend the system test environment.

**Comment by timtebeek** [comment]
Thanks; Now have access to the test env.
