### ISSUE TITLE
Question: How to retrieve credit card transactions?

### ISSUE THREAD

**Issue by timtebeek** [Ceskasporitelna/WebAPI#11]
Hi! How do I retrieve credit card transactions? The documentation just lists that these are not available, but I'd like to access them in some way.

**Comment by jmachan** [comment]
Hi Tim! Which API are you asking about? [Netbanking](https://developers.csas.cz/docs/netbanking-v3) or [Corporate](https://developers.csas.cz/docs/corporate-v1)?

**Comment by timtebeek** [comment]
Hi! Netbanking please.. :)

**Comment by timtebeek** [comment]
Any update on this @jmachan?

**Comment by jmachan** [comment]
@timtebeek It's a feature which is now unavailable for the 3rd parties. Trying to find some workaround for you.

**Comment by timtebeek** [comment]
Closing for lack of response.
