### ISSUE TITLE
Questions about netbanking account transactions

### ISSUE THREAD

**Issue by timtebeek** [Ceskasporitelna/WebAPI#12]
Hi all,

A couple of questions about retrieving account transactions through the netbanking API:
- are all transactions automatically booked, or can some still be pending? How can I tell?
- for account transactions the API docs do not list what returned values are mandatory/optional as with most other calls; can you update the docs to include this?
- the account transactions call in the documentation/sandbox does not list pagination parameters as most other calls do, is it supported?

Thanks in advance!

**Comment by timtebeek** [comment]
Also: The accounts/transactions appears to ignore my page parameter for pagination; Is that something you can fix on your end?

**Comment by petrdvorak** [comment]
@timtebeek Hello Tim, fellow WebAPI integrator here... :) I suggest you move from "sandbox" to "test" environment as fast as possible. You can apply for the test API key from the developer portal contact form.

The sandbox environment apparently uses "hand written mocks" (transaction ID not unique, only two same pages, etc.). These are little bit buggy and do not update with API changes. Test environment, however, uses actual live API and is much better for the development...

**Comment by jmachan** [comment]
Hey guys! It's precisely as @petrdvorak wrote. Sandbox is just and only for the very first contact with our API, so the mocks are static. @timtebeek System Test environment will definitely work better for you.

**Comment by timtebeek** [comment]
Great, thanks; Will switch to the test env; Updated my comments above; Can you answer the remaining questions?

**Comment by timtebeek** [comment]
Closing for lack of response.
