### ISSUE TITLE
Consider adding more information about the user in /my/profile

### ISSUE THREAD

**Issue by petrdvorak** [Ceskasporitelna/WebAPI#5]
Currently, information about user that is provided in `/my/profile` endpoint is limited.

It would be nice to extend the endpoint to include:

- permanent residence address
- contact address
- birth ID
- contact information (e-mail, phone number)

Of course, the issue with providing these pieces of information is in personal data protection. Therefore, user would have to give an explicit consent before the bank can provide it (which can be solved in scope of issue #4)...

**Comment by jmachan** [comment]
These informations are located in the Intrabanking API which is now strictly internal. We would like to introduce the wider scope of user's data in the future, but now we're unable to open it.
