### ISSUE TITLE
Chyba 404 se vrací, když se odkazujete na neexistující endpoint nebo resource, v případě výpisu na základě kritérií by se měla vracet prázdná data

### ISSUE THREAD

**Issue by michaltoman** [Ceskasporitelna/WebAPI#8]
Jedná se o výpisy poboček, bankomatů, ...

Dotaz např.: https://api.csas.cz/sandbox/webapi/api/v2/places/branches?q=Mladkov

q = Mladkov

Čekal bych intuitivně prázdné pole, nikoli chybu 404.

Jako příklad si můžete zkusit drip, který vrací prázdné pole, a 404 při odkazu na neexistující endpoint nebo resource 

https://www.getdrip.com/docs/rest-api

Odkazujete se na konvence: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

Ale dle nás došlo k jejich jemné dezinterpretaci.

Podívejte se na to i z pohledu klienta.

Klient zadá Mladkov do q. Vrátí mu to chybu 404. Začne reportovat issue na support, že Vaše služba vlastně vůbec nechodí a že je rozbitá. My jako Integromat se svezeme s Vámi. To nám klienti totiž běžně reportují.

S pozdravem, Michal Toman
(Integromat)

**Comment by rsmichovic** [comment]
Dobrý den,
díky za upozornění a připomínky.
V současnosti rozlišujeme URL NOT Found (v případě zcela špatné adresy):
`{
   "status": 404,
  "errors": [
    {
      "error": "endpoint not found"
    }
  ]
}`

oproti odpovědi aplikačního BE
`{
  "error": {
    "statusCode": 404,
    "status": "Not Found"
  }
}`

Takže alespoň základní rozlišení zda jde o chybu nebo data nebyla nalezena tady ted je.

Máte pravdu, že odpověď BE je v tomto případě ne zcela šťastná. 
Problému se budeme věnovat.

**Comment by michaltoman** [comment]
Děkuji za reakci.

Problém je skutečně v tom, že ty konvence jsou docela vágní, takže si to
každý vykládá po svém.

https://www.drip.co  to mají jako my.

https://www.messagebird.com se blíží Vaší implementaci.

Tak jako tak si myslíte, jak píšete Vy, že chyba 404 pro žádná data není
úplně vhodně zvolená. Ale nemáme právo Vás tlačit k nějaké změně. Bude toto
rozhodnutí skutečně na Vás, k jaké straně se přikloníte.

Z pohledu uživatele je asi skutečně lepší žádná data ošetřit prázdným polem.

S pozdravem, Michal Toman
(Integromat)

Dne 28. dubna 2017 13:31 rsmichovic <notifications@github.com> napsal(a):

**Comment by michaltoman** [comment]
Ale i tak u MessageBirdu to mají tak, že 404 vrací, když se odkazuji na
neexistující message. Když vracím list zpráv, tak to vrací prázdné pole.

Dne 28. dubna 2017 15:53 Michal Toman <michal.toman.phd@gmail.com>
napsal(a):

**Comment by rsmichovic** [comment]
Dobrý den,
ještě jednou díky za připomínky a argumentaci.
Trochu nás zdrželo, že jsme se problému museli věnovat globálněji (ověřovali jsme i ostatní API a naše standardy).

API v dohledné době upravíme dle Vašeho návrhu, protože v tomto případě jsme shledali, že Vámi popsané chování je smysluplnější.

**Comment by rsmichovic** [comment]
Naposledy dobrý den,
oprava je již nasazena na testovacím prostředí.
Na produkci a v sandboxu se projeví po migraci plánované v půli května.

**Comment by michaltoman** [comment]
Rádi Váš release v druhé polovině května otestujeme a těšíme se na výsledek.

S pozdravem, Michal Toman

2017-05-05 10:43 GMT+02:00 rsmichovic <notifications@github.com>:

**Comment by rsmichovic** [comment]
Dobrý den,
včera byla nasazena nová verze, která by se měla projevit jak na sandboxu tak na produkčním prostředí. 
Budeme rádi, když vyzkoušíte a dáte nám vědět.
S pozdravem Rudy Smichovič

**Comment by michaltoman** [comment]
Dobrý den,

1) 40x vs. prázdné pole:

vypadá, že funguje dle přestav. Prázdné pole vs. výsledky - Ok.

Když není jedna ze souřadnic [špatná kritéria], tak to hází chybu 400. To
už je dle očekávání.

2) Otestoval jsem s tím i konkrétní výsledky:

Porovnával jsem i proti vyhledávání na zeměpisnou šířku a délku a vrací to
podobné výsledky.

Kritéria Praha vs. 50.05,14.25 a okruh 15000 vrací přibližně stejné
výsledky.

S pozdravem, Michal Toman

2017-05-18 13:06 GMT+02:00 rsmichovic <notifications@github.com>:
