### ISSUE TITLE
Unable to get transactions. Bad documentation?

### ISSUE THREAD

**Issue by Jecma** [Ceskasporitelna/WebAPI#9]
There is nice list o transactions i want to get in Example response for "Get account transaction", but "Try" (and my localhost) return different response.
[`Example`](https://developers.csas.cz/docs/netbanking-v3#/reference/accounts/account-transactions-history/get-account-transactions.)
Response:
`{
  "pageNumber": 0,
  "pageCount": 2,
  "nextPage": 1,
  "pageSize": 100,
  "transactions": [
    {
      "accountParty": {
        "accountNumber": "2812275553",
        "accountPrefix": "0",
        "bankCode": "0800",
        "bic": "GIBACZPX",
        "iban": "CZ2908000000002812275553",
        "partyInfo": "Petr Malý",
        "partyDescription": "2812275553/0800"
      },
      "amount": {
        "currency": "CZK",
        "precision": 2,
        "value": 100
      },
      "amountSender": {
        "currency": "CZK",
        "precision": 2,
        "value": 100
      },
      "bookingDate": "2014-11-26T00:00:00+01:00",
      "cardNumber": 0,
      "constantSymbol": "0558",
      "description": "domácí platba",
      "descriptionEditable": "false",
      "id": "I141126DXHZ3T",
      "payeeNote": "note for payee",
      "payerNote": "note for payer",
      "specificSymbol": "55",
      "transactionType": "54",
      "valuationDate": "2014-11-26T00:00:00+01:00",
      "variableSymbol": "0000000009"
    }
  ]
}`
['Try example'](https://developers.csas.cz/docs/netbanking-v3#/reference/accounts/account-transactions-history/get-account-transactions.?console=1)
`{
  "limits": [
    {
      "id": "934872973982",
      "authorizationType": "TAC",
      "channelId": "NET_BANKING",
      "applicationId": "GEORGE",
      "dailyLimit": {
        "value": 400000,
        "precision": 2,
        "currency": "EUR"
      },
      "transactionLimit": {
        "value": 100000,
        "precision": 2,
        "currency": "EUR"
      },
      "maxBankLimit": {
        "value": 1700000,
        "precision": 2,
        "currency": "EUR"
      }
    },
    {
      "id": "934872973987",
      "authorizationType": "TAC",
      "channelId": "NET_BANKING",
      "applicationId": "INTERNET_BANKING",
      "dailyLimit": {
        "value": 150000,
        "precision": 2,
        "currency": "EUR"
      },
      "transactionLimit": {
        "value": 90000,
        "precision": 2,
        "currency": "EUR"
      },
      "maxBankLimit": {
        "value": 900000,
        "precision": 2,
        "currency": "EUR"
      }
    }
  ]`
Have no idea how to get my transactions

**Comment by petrdvorak** [comment]
@ceskasporitelna Mock API / documentation issue. Documentation does not match example.

@Jecma If you work with actual WebAPI key and OAuth credentials, and use non-demo account, everything works. The issue with mock / demo space on Apiary is that it's backed by the static (read "txt-like") files that sometimes do not match the correct resource... From my experience, I suggest you jump on actual live resources as soon as possible.

**Comment by jarda-mlejnek** [comment]
@Jecma The mock issue is fixed. The endpoint returns appropriate response.
@petrdvorak Thanks for your help ;-)

**Comment by jmachan** [comment]
Thx everybody for participating in resolving this issue!
